INSERT INTO submissions (poll_id, submitter_name)
VALUES (1, 'Ash'),
      (1, 'Michael'),
      (1, 'Joe'),
      (2, 'Andy'),
      (2, 'Travis'),
      (2, 'Gary'),
      (3, 'Brian'),
      (3, 'Paul'),
      (3, 'James'),
      (3, 'Jerry'),
      (3, 'Simon'),
      (4, 'Gary'),
      (4, 'Alice'),
      (5, 'Michael'),
      (5, 'Joe'),
      (5, 'Ashley'),
      (6, 'Emma');
