DROP TABLE IF EXISTS choices CASCADE;
DROP TABLE IF EXISTS options CASCADE;
CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES polls(id),
  option_name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);
